services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - ./Architecture/database.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build: ./Backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/app_dentaire?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./FRONTEND
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
